model:
  base_learning_rate: 8.0e-6
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 128
    ortho_reg_coef: 0.0   # 0.0 or 10.0
    force_emb_len_1: False
    distance_measure: L2     # [L2, cos_sim]
    eq_metric_dataset: mnist
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 64
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,2]
      num_res_blocks: 1
      attn_resolutions: [16]
      dropout: 0.0
      downsampling_method: strided_conv   # [strided_conv, convblurpool, maxpool, maxblurpool]
      use_replicationpad: True
      version: v2

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 96
    num_workers: 8
    train:
      target: taming.data.mnist.MnistTrain
      params:
        size: 64
        crop_size: 64
    validation:
      target: taming.data.mnist.MnistValidation
      params:
        size: 64
        crop_size: 64
